### ISSUE TITLE
Drupal 9 has updated to Symfony 4.

### ISSUE THREAD

**Issue by luzzardi** [aklump/loft_data_grids#4]
Drupal 9 update to symfony 4 and future drupal 10 will update to symfony 5.
Could we update the dependency. to be:
 ```
"symfony\/yaml": "^3.4 || ^4 || ˆ5",
```

**Comment by luzzardi** [comment]
Hi @aklump could you take a look on this?

**Comment by aklump** [comment]
@luzzardi Thank you for the help. I've made this adjustment in 0.5.3.

**Comment by luzzardi** [comment]
Thanks!
